modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/VazkiiMods/Quark"
license="https://github.com/Vazkii/QuarkMods/blob/master/LICENSE.md"

[[mods]]
modId="quark"
displayName="Quark"
version="${file.jarVersion}"
authors="Vazkii, WireSegal, MCVinnyq, Sully"
description='''Small things, improving Minecraft bit by bit.'''

[[dependencies.quark]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.8,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quark]]
    modId="zeta"
    mandatory=false
    versionRange="[${zeta_ver},2.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.quark]]
    modId="lootr"
    mandatory=false
    versionRange="[0.4.24.61,)"
    ordering="AFTER"
    side="BOTH"
